return {
  {
    "catppuccin/nvim",
    priority = 1000,
    name = "catppuccin",
    opts = {
      transparent_background = true,
      color_overrides = {
        latte = {
          rosewater = "#c14a4a",
          flamingo = "#c14a4a",
          red = "#c14a4a",
          maroon = "#c14a4a",
          pink = "#945e80",
          mauve = "#945e80",
          peach = "#c35e0a",
          yellow = "#b47109",
          green = "#6c782e",
          teal = "#4c7a5d",
          sky = "#4c7a5d",
          sapphire = "#4c7a5d",
          blue = "#45707a",
          lavender = "#45707a",
          text = "#654735",
          subtext1 = "#73503c",
          subtext0 = "#805942",
          overlay2 = "#8c6249",
          overlay1 = "#8c856d",
          overlay0 = "#a69d81",
          surface2 = "#bfb695",
          surface1 = "#d1c7a3",
          surface0 = "#e3dec3",
          base = "#f9f5d7",
          mantle = "#f0ebce",
          crust = "#e8e3c8",
        },
        mocha = {
          base = "#1d2021",
          blue = "#7daea3",
          crust = "#141617",
          flamingo = "#ea6962",
          green = "#a9b665",
          lavender = "#7daea3",
          mantle = "#191b1c",
          maroon = "#ea6962",
          mauve = "#d3869b",
          overlay0 = "#595959",
          overlay1 = "#928374",
          overlay2 = "#a89984",
          peach = "#e78a4e",
          pink = "#d3869b",
          red = "#ea6962",
          rosewater = "#ea6962",
          sapphire = "#89b482",
          sky = "#89b482",
          subtext0 = "#bdae93",
          subtext1 = "#d5c4a1",
          surface0 = "#292929",
          surface1 = "#404040",
          surface2 = "#4d4d4d",
          teal = "#89b482",
          text = "#ebdbb2",
          yellow = "#d8a657",
        },
      },
      integrations = {
        blink_cmp = true,
        dadbod_ui = true,
        diffview = true,
        grug_far = true,
        mason = true,
        nvim_surround = true,
        overseer = true,
        native_lsp = {
          enabled = true,
          virtual_text = {
            errors = { "italic" },
            hints = { "italic" },
            warnings = { "italic" },
            information = { "italic" },
          },
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
          inlay_hints = {
            background = true,
          },
        },
        which_key = true,
      },
    },
  },
}
