name: update packages
on:
  schedule:
    - cron: 22 2 * * *
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install neovim
        run: sudo apt install -y neovim git curl wget luajit build-essential

      - name: Update packages
        run: nvim --headless -u init.lua +q

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "plugin(s)(ci): auto-updated"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
